name: Build and Release to GitHub Packages

on:
  push:
    branches:
      - master
      - prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Packages
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login gcr.io -u ${{ github.actor }} --password-stdin

    - name: Determine Docker tag
      id: tag
      run: |
        if [[ "${GITHUB_REF}" == "refs/heads/master" ]]; then
          echo "latest"
        elif [[ "${GITHUB_REF}" == "refs/heads/prod" ]]; then
          echo "prod"
        else
          echo "unknown"
        fi
      shell: bash

    - name: Build and push Docker image
      run: |
        docker buildx build --platform linux/amd64 --build-arg BINARY_NAME_DEFAULT=${{ env.BINARY_NAME_DEFAULT }} -t gcr.io/${{ github.repository_owner }}/${{ github.repository_name }}:${{ steps.tag.outputs.tag }} -t gcr.io/${{ github.repository_owner }}/${{ github.repository_name }}:${{ github.sha }} .
        docker push gcr.io/${{ github.repository_owner }}/${{ github.repository_name }}:${{ steps.tag.outputs.tag }}
        docker push gcr.io/${{ github.repository_owner }}/${{ github.repository_name }}:${{ github.sha }}
