name: Build and Deploy Rust to Server

on:
  workflow_dispatch:  # Trigger manually

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl
          components: rustfmt, clippy

      - name: Build Rust project
        run: cargo build --release --target x86_64-unknown-linux-musl

      - name: Get SSH key
        env:
          SSH_KEY_SECRET: ${{ secrets.SSH_PRIVATE_KEY }}
        run: echo "$SSH_KEY_SECRET" > ~/.ssh/id_rsa
        run: chmod 600 ~/.ssh/id_rsa

      - name: Add known host
        run: ssh-keyscan panel.billdivide.app >> ~/.ssh/known_hosts

      - name: Deploy binary
        run: scp target/x86_64-unknown-linux-musl/release/deepsplit_be billdivide@panel.billdivide.app:~/development/
